---
- name: Install pipx and its dependencies
  hosts: all

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update package list (Debian-based)
      become: true
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Update package list (Redhat-based)
      become: true
      ansible.builtin.yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Install Python 3 and pip on Debian-based systems
      become: true
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Python 3 and pip on RedHat-based systems
      become: true
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Pipx
      ansible.builtin.pip:
        name: pipx
        extra_args: --user

    - name: Install Ansible using pipx
      community.general.pipx:
        name: "{{ package_name }}"
        install_deps: true
